development:
  adapter: redis
  url: redis://redis-18181.c10.us-east-1-2.ec2.cloud.redislabs.com:18181/

test:
  adapter: async

production:
  adapter: redis
  url: redis://redis-18181.c10.us-east-1-2.ec2.cloud.redislabs.com:18181/
