# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f7db63fda6590165b359f16258dba0825bdb007be3b574db251764f9220fe8ff9b9a24a012c1c5f7a93643b8e67f8c4ffae6275fb2edd25b15314e9af1702b7

test:
  secret_key_base: f298807c6e615e3beb8161fb15e2963f828110656b10c72a3265fe2d0b4b85b2a14c09da22db9dc9715f395eb81cdb56fa5a2ab272a6d470071aa61f2856796c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
